"""Key on email in users table

Revision ID: cfaf21caa00b
Revises: ed3110b30b84
Create Date: 2017-01-21 19:44:01.269806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfaf21caa00b'
down_revision = 'ed3110b30b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_email_unique_constraint', 'users', ['email'])
    op.add_column('rep_exercises_history', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_constraint(u'rep_exercises_history_user_id_fkey', 'rep_exercises_history', type_='foreignkey')
    op.create_foreign_key(u'rep_exercises_history_user_email_fkey', 'rep_exercises_history', 'users', ['user_email'], ['email'])
    op.drop_column('rep_exercises_history', 'user_id')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), primary_key=True))
    op.create_unique_constraint(u'users_id_unique_constraint', 'users', ['id'])
    op.add_column('rep_exercises_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(u'rep_exercises_history_user_email_fkey', 'rep_exercises_history', type_='foreignkey')
    op.create_foreign_key(u'rep_exercises_history_user_id_fkey', 'rep_exercises_history', 'users', ['user_id'], ['id'])
    op.drop_constraint(u'users_email_unique_constraint', 'users', type_='unique')
    op.drop_column('rep_exercises_history', 'user_email')
    # ### end Alembic commands ###
