"""Key users on email address

Revision ID: eff616bd38f1
Revises: ed3110b30b84
Create Date: 2017-01-21 19:30:08.421826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff616bd38f1'
down_revision = 'ed3110b30b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'rep_exercises_history_user_id_fkey', 'rep_exercises_history', type_='foreignkey')
    op.create_foreign_key(None, 'rep_exercises_history', 'users', ['user_id'], ['email'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'rep_exercises_history', type_='foreignkey')
    op.create_foreign_key(u'rep_exercises_history_user_id_fkey', 'rep_exercises_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
